# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.provision :shell,
    path: "../../shared/config.sh",
    name: "Configuring environment"
  config.vm.provision :shell,
    path: "../../shared/bootstrap.sh",
    name: "Bootstrapping OS"
  config.vm.provision :shell,
    path: "../../shared/lighttpd/lighttpd.sh",
    name: "Installing Lighttpd"
  config.vm.provision :shell,
    path: "../../shared/php/php7-fpm.sh",
    name: "Configuring for PHP 7"
  config.vm.provision :shell,
    path: "../../shared/users.sh",
    name: "Creating users"
  config.vm.provision :shell,
    path: "./pirum.sh",
    name: "Creating Pirum install"
end
