# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/precise64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision :shell, path: "../../shared/config.sh"
  config.vm.provision :shell, path: "../../shared/bootstrap.sh"
  config.vm.provision :shell, path: "../../shared/php54.sh"
  config.vm.provision :shell, path: "../../shared/users.sh"
  config.vm.provision :shell, path: "../../shared/mysql.sh"
  config.vm.provision :shell, path: "../../shared/dovecot.sh"
  config.vm.provision :shell, path: "../../shared/postfix_local.sh"
  config.vm.provision :shell, path: "../../shared/procmail.sh"
  config.vm.provision :shell, path: "../../shared/vsftpd.sh"
  config.vm.provision :shell, path: "horde.sh"
end
