# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/yakkety64"
  config.vm.network "public_network", ip: "192.168.1.52"
  config.vm.provision :shell,
    path: "./conf.sh",
    name: "Configuring environment"
  config.vm.provision :shell,
    path: "./bootstrap.sh",
    name: "Bootstrapping OS"
  config.vm.provision :shell,
    path: "../../shared/postfix/postfix_local.sh",
    name: "Installing Postfix and configuring for local delivery only."
  config.vm.provision :shell,
    path: "./cyrus.sh",
    name: "Installing Cyrus"
  config.vm.provision :shell,
    path: "./cyrus_users.sh",
    name: "Creating Cyrus users"
end