# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.network "public_network", ip: "192.168.1.55"
  #config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.hostname = "horde-master.local"

  if Vagrant.has_plugin?('vagrant_hostsupdater')
    config.hostsupdater.aliases = ["www.horde-master.local"]
    config.hostsupdater.remove_on_suspend = true
  end

  # Attempt to give appropriate amount of RAM
  # Gives 1/4 system ram by default. Adjust as needed.
  config.vm.provider "virtualbox" do |v|
    host = RbConfig::CONFIG['host_os']

    # Give VM 1/4 system memory
    if host =~ /darwin/
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif host =~ /linux/
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i
    elsif host =~ /mswin|mingw|cygwin/
      # Windows code via https://github.com/rdsubhas/vagrant-faster
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end
    mem = mem / 1024 / 4
    v.customize ["modifyvm", :id, "--memory", mem]
  end

  # If host is able, use nfs for better performance.
  # Requires [public|private]_networking
  # config.vm.synced_folder '.', '/vagrant', nfs: true
  #config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/", rsync__auto: true
  config.vm.provision :shell,
    path: "../../shared/config.sh",
    name: "Configuring environment"
  config.vm.provision :shell,
    path: "dev_config.sh",
    name: "Configuring development specific settings"
  config.vm.provision :shell,
    path: "webroot.sh",
    name: "Setting webroot"
  config.vm.provision :shell,
    path: "hordedirectory.sh",
    name: "Setting hordedirectory"
  config.vm.provision :shell,
    path: "../../shared/bootstrap.sh",
    name: "Bootstrapping OS"
  config.vm.provision :shell,
    path: "../../shared/php/php73-fpm.sh",
    name: "Configuring for PHP 7-fpm"
  config.vm.provision :shell,
    path: "../../shared/nginx/nginx.sh",
    name: "Installing NGINX"
  config.vm.provision :shell,
    path: "../../shared/users.sh",
    name: "Creating users"
  config.vm.provision :shell,
    path: "../../shared/mysql/mysql.sh",
    name: "Installing MySQL"
  config.vm.provision :shell,
    path: "../../shared/dovecot/dovecot.sh",
    name: "Installing Dovecot"
  config.vm.provision :shell,
    path: "../../shared/postfix/postfix_local.sh",
    name: "Installing Postfix and configuring for local delivery only."
  config.vm.provision :shell,
    path: "../../shared/postfix/procmail.sh",
    name: "Installing Procmail"
  config.vm.provision :shell,
    path: "../../shared/vsftpd.sh",
    name: "Installing vsftp"
  config.vm.provision :shell,
    path: "../../shared/Composer/composer.sh",
    name: "Installing Composer"
  config.vm.provision :shell,
    path: "../../shared/horde-git-tools.sh",
    name: "Installing horde-git-tools"
  config.vm.provision :shell,
    path: "horde.sh",
    name: "Installing Horde"

  if File.exists?(File.join(File.dirname(__FILE__), 'provision-post.sh')) then
    config.vm.provision :shell, :privileged => false, :path => File.join(File.dirname(__FILE__), 'provision-post.sh')
  end

end
