# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.hostname = "horde-master.local"
  config.hostsupdater.aliases = ["www.horde-master.local"]
  config.vm.provision :shell,
    path: "../../shared/config.sh",
    name: "Configuring environment"
  config.vm.provision :shell,
    path: "dev_config.sh",
    name: "Configuring development specific settings"
  config.vm.provision :shell,
    path: "../../shared/bootstrap.sh",
    name: "Bootstrapping OS"
  config.vm.provision :shell,
    path: "../../shared/php/php73-fpm.sh",
    name: "Configuring for PHP 7-fpm"
  config.vm.provision :shell,
    path: "../../shared/nginx/nginx.sh",
    name: "Installing NGINX"
  config.vm.provision :shell,
    path: "../../shared/users.sh",
    name: "Creating users"
  config.vm.provision :shell,
    path: "../../shared/mysql/mysql.sh",
    name: "Installing MySQL"
  config.vm.provision :shell,
    path: "../../shared/dovecot/dovecot.sh",
    name: "Installing Dovecot"
  config.vm.provision :shell,
    path: "../../shared/postfix/postfix_local.sh",
    name: "Installing Postfix and configuring for local delivery only."
  config.vm.provision :shell,
    path: "../../shared/postfix/procmail.sh",
    name: "Installing Procmail"
  config.vm.provision :shell,
    path: "../../shared/vsftpd.sh",
    name: "Installing vsftp"
  config.vm.provision :shell,
    path: "../../shared/Composer/composer.sh",
    name: "Installing Composer"
  config.vm.provision :shell,
    path: "../../shared/horde-git-tools.sh",
    name: "Installing horde-git-tools"
  config.vm.provision :shell,
    path: "horde.sh",
    name: "Installing Horde"
end
